sudo clab-telemetry-linker set -n XR-1 -i Gi0-0-0-1 
sudo clab-telemetry-linker set -n XR-1 -i Gi0-0-0-2 
sudo clab-telemetry-linker set -n XR-2 -i Gi0-0-0-0
sudo clab-telemetry-linker set -n XR-2 -i Gi0-0-0-1
sudo clab-telemetry-linker set -n XR-3 -i Gi0-0-0-0
sudo clab-telemetry-linker set -n XR-3 -i Gi0-0-0-3
sudo clab-telemetry-linker set -n XR-5 -i Gi0-0-0-1 
sudo clab-telemetry-linker set -n XR-5 -i Gi0-0-0-2
sudo clab-telemetry-linker set -n XR-6 -i Gi0-0-0-2
sudo clab-telemetry-linker set -n XR-6 -i Gi0-0-0-0
sudo clab-telemetry-linker set -n XR-6 -i Gi0-0-0-1 
sudo clab-telemetry-linker set -n XR-6 -i Gi0-0-0-2
sudo clab-telemetry-linker set -n XR-6 -i Gi0-0-0-3
sudo clab-telemetry-linker set -n XR-6 -i Gi0-0-0-4
sudo clab-telemetry-linker set -n XR-7 -i Gi0-0-0-0
sudo clab-telemetry-linker set -n XR-7 -i Gi0-0-0-1
sudo clab-telemetry-linker set -n XR-7 -i Gi0-0-0-2 
sudo clab-telemetry-linker set -n XR-7 -i Gi0-0-0-3
sudo clab-telemetry-linker set -n XR-7 -i Gi0-0-0-4 
sudo clab-telemetry-linker set -n XR-8 -i Gi0-0-0-0
sudo clab-telemetry-linker set -n XR-8 -i Gi0-0-0-1 
sudo clab-telemetry-linker set -n XR-8 -i Gi0-0-0-2 
sudo clab-telemetry-linker set -n XR-8 -i Gi0-0-0-3
sudo clab-telemetry-linker set -n SITE-B -i Gi0-0-0-0 
sudo clab-telemetry-linker set -n SITE-B -i Gi0-0-0-2
sudo clab-telemetry-linker set -n SITE-C -i Gi0-0-0-2 
